services:
  - type: web
    name: dsa-patterns
    env: node
    buildCommand: yarn install && yarn build
    startCommand: serve -s build
    envVars:
      - key: NODE_ENV
        value: production
    healthCheckPath: /
    autoDeploy: true 